# Generated by Django 3.2.8 on 2021-10-10 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_answer_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('id',)},
        ),
    ]
