# Generated by Django 3.2.8 on 2021-10-10 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('name', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('beginner', 'начинающий'), ('experienced', 'опытный'), ('expert', 'эксперт'), ('profi', 'профи')], max_length=16)),
                ('picture_id', models.PositiveSmallIntegerField(default=1)),
                ('coins', models.PositiveBigIntegerField(default=10)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
