# Generated by Django 3.2.8 on 2021-10-10 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='status',
            field=models.CharField(choices=[('beginner', 'начинающий'), ('experienced', 'опытный'), ('expert', 'эксперт')], default='beginner', max_length=16),
        ),
    ]
