# Generated by Django 3.2.8 on 2021-10-10 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20211010_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='status',
            field=models.CharField(choices=[('newbie', 'начинающий'), ('expirienced', 'опытный'), ('expert', 'эксперт')], default='newbie', max_length=16),
        ),
    ]
